version: '3.8'

services:
  nuxt:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nuxt
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.nest
    environment:
      - NODE_ENV=production
      - REDIS_URI=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
